.TH ANNOUNCELOGIC.CONF 5 "November 2022" Linux "File Formats"
.
.SH NAME
.
AnnounceLogic.conf \- AnnounceLogic configuration file for the SvxLink server
.
.SH DESCRIPTION
.
.B svxlink
is a general purpose voice service system for ham radio use. This man-page
describe the SvxLink server configuration file format for the AnnounceLogic logic
core.
.
.SH CONFIGURATION VARIABLES
.
Here is the description of all configuration variables that the AnnounceLogic
SvxLink logic core understands. The configuration variables are described
section for section.
.
.SS AnnounceLogic
.
The AnnounceLogic is used to stream broadcasts into other logics or into a
repeater network.
.TP
.B TYPE
The type for a announce logic core is always
.BR Announce
.TP
.B START_PRENOTIFICATION_MINUTES_BEFORE
Define the minutes before the start time of the broadcast message.
.TP
.B PRENOTIFICATION_INTERVAL
The interval in minutes between the time calculated from the paramter
START_PRENOTIFICATION_MINUTES_BEFORE and the start time of the broadcast
messages.
.TP
.B DAY_OF_WEEK
The number of the day of week (0=Sunday, 1= Monday, ..., 6=Saturday) when the
broadcast message will be started.
.TP
.B DAYS_IN_MONTH
Defined the day of month when the braodcast messages will be started.
DAYS_IN_MONTH=1,3 means 1st and 3rd DAY_OF_WEEK in month.
.TP
.B HOUR_OF_QST
Hour (time) when the broadcast is started.
.TP
.B MINUTE_OF_QST
Minute (time) when the broadcast is started.
.TP
.B EVENT_HANDLER
Point out the TCL event handler script to use. The TCL event handler script is
responsible for playing the correct audio clips when an event occur.
The default location is /usr/share/svxlink/events.tcl
.
.SH FILES
.
.TP
.IR /etc/svxlink/svxlink.d/AnnounceLogic.conf
The AnnounceLogic specific configuration file.
.TP
.IR /etc/svxlink/svxlink.conf
The system wide configuration file.
.TP
.IR ~/.svxlink/svxlink.conf
Per user configuration file.
.TP
.I /etc/svxlink/svxlink.d/*
Additional configuration files. Typically one configuration file per module.
.
.SH AUTHOR
.
Adi Bier (DL1HRC)
.
.SH "SEE ALSO"
.
.BR svxlink.conf (5)
