EchoLib: EchoLink::StationData Class Reference
EchoLink::StationData Class Reference
A class for representing data for a station.
#include <EchoLinkStationData.h>
Public Types
enum Status { STAT_UNKNOWN , STAT_OFFLINE , STAT_ONLINE , STAT_BUSY }
Public Member Functions
StationData (void)
Default constructor.
StationData (const StationData &rhs)
Copy constructor.
void clear (void)
Clear the contents and reset to default values.
void setCallsign (const std::string &callsign)
Set the callsign.
const std::string & callsign (void) const
Get the callsign.
void setData (const char *data)
Set station data from a string as represented in the directory server.
void setStatus (Status status)
Set the status.
Status status (void) const
Get the status.
std::string statusStr (void) const
Return the string representation of the status.
void setTime (const std::string &time)
Set the time.
const std::string & time (void) const
Get the time.
void setDescription (const std::string &desc)
Set the description/location string.
const std::string & description (void) const
Get the description/location string.
void setId (int id)
Set the EchoLink ID number.
int id (void) const
Get the EchoLink ID number.
void setIp (const Async::IpAddress &ip)
Set the IP address.
const Async::IpAddress ip (void) const
Get the IP address.
std::string ipStr (void) const
Get the string representation of the IP address.
std::string code (void) const
Get the code representation of the callsign.
StationData & operator= (const StationData &rhs)
Assignment operator.
bool operator< (const StationData &rhs) const
Static Public Member Functions
static std::string statusStr (Status status)
Translate a status code to a string.
Static Public Attributes
static const int MAXCALL = 15
The maximum length of a callsign.
static const int MAXDATA = 45
The maximum length of the data field.
static const int MAXDESC = 27
The maximum length of a description.
static const int MAXID = 7
The maximum length of the id field.
static const int MAXIP = 20
The maximum length of the ip address.
Friends
std::ostream & operator<< (std::ostream &os, const StationData &station)
Output stream operator.
Detailed Description
A class for representing data for a station.
Author
Tobias Blomberg
Date
2003-04-13
This class is used to represent data about a station.
Examples
EchoLinkDirectory_demo.cpp.
Definition at line 108 of file EchoLinkStationData.h.
Member Enumeration Documentation
Status
enum EchoLink::StationData::Status
The status of the station in the directory server
Enumerator
STAT_UNKNOWN
The state is unknown.
STAT_OFFLINE
The state is offline.
STAT_ONLINE
The state is online.
STAT_BUSY
The state is busy.
Definition at line 114 of file EchoLinkStationData.h.
Constructor & Destructor Documentation
StationData() [1/2]
EchoLink::StationData::StationData (void)
Default constructor.
StationData() [2/2]
EchoLink::StationData::StationData (const StationData & rhs) inline
Copy constructor.
Definition at line 143 of file EchoLinkStationData.h.
Member Function Documentation
callsign()
const std::string & EchoLink::StationData::callsign (void) const inline
Get the callsign.
Returns
Returns the callsign
Definition at line 160 of file EchoLinkStationData.h.
clear()
void EchoLink::StationData::clear (void)
Clear the contents and reset to default values.
code()
std::string EchoLink::StationData::code (void) const inline
Get the code representation of the callsign.
Returns
Returns the code representation of the callsign
The code representation is the callsign mapped to digits only. The mapping is done using the "phone method". ABC=2, DEF=3, GHI=4, JKL=5, MNO=6, PQRS=7, TUV=8, WXYZ=9. Digits are mapped to its corresponding digit. Star is ignored. All other characters are mapped to digit 1.
Definition at line 259 of file EchoLinkStationData.h.
description()
const std::string & EchoLink::StationData::description (void) const inline
Get the description/location string.
Returns
Returns the description/location string
Definition at line 215 of file EchoLinkStationData.h.
id()
int EchoLink::StationData::id (void) const inline
Get the EchoLink ID number.
Returns
Returns the EchoLink ID number
Definition at line 227 of file EchoLinkStationData.h.
Referenced by setId().
ip()
const Async::IpAddress EchoLink::StationData::ip (void) const inline
Get the IP address.
Returns
Returns the IP address
Definition at line 239 of file EchoLinkStationData.h.
Referenced by setIp().
ipStr()
std::string EchoLink::StationData::ipStr (void) const inline
Get the string representation of the IP address.
Returns
Returns the string representation of the IP address
Definition at line 245 of file EchoLinkStationData.h.
operator<()
bool EchoLink::StationData::operator< (const StationData & rhs) const inline
Definition at line 268 of file EchoLinkStationData.h.
operator=()
StationData & EchoLink::StationData::operator= (const StationData & rhs)
Assignment operator.
Parameters
rhs Right Hand Side expression
Returns
Returns a reference to this object
setCallsign()
void EchoLink::StationData::setCallsign (const std::string & callsign)
Set the callsign.
Parameters
callsign The callsign to set
setData()
void EchoLink::StationData::setData (const char * data)
Set station data from a string as represented in the directory server.
Parameters
data The data to set
This function is used to set status, time and description from a string that have a representation like in the reply from the directory server. The only use for this function is probably when parsing a reply from the directory server. Use setStatus, setTime and setDescription for normal use.
setDescription()
void EchoLink::StationData::setDescription (const std::string & desc) inline
Set the description/location string.
Parameters
desc The description string to set
Definition at line 209 of file EchoLinkStationData.h.
setId()
void EchoLink::StationData::setId (int id) inline
Set the EchoLink ID number.
Parameters
id The new id
Definition at line 221 of file EchoLinkStationData.h.
References id().
setIp()
void EchoLink::StationData::setIp (const Async::IpAddress & ip) inline
Set the IP address.
Parameters
ip The IP address to set
Definition at line 233 of file EchoLinkStationData.h.
References ip().
setStatus()
void EchoLink::StationData::setStatus (Status status) inline
Set the status.
Parameters
status The new status to set
Definition at line 179 of file EchoLinkStationData.h.
References status().
setTime()
void EchoLink::StationData::setTime (const std::string & time) inline
Set the time.
Parameters
time The time to set
Definition at line 197 of file EchoLinkStationData.h.
References time().
status()
Status EchoLink::StationData::status (void) const inline
Get the status.
Returns
Returns the status
Definition at line 185 of file EchoLinkStationData.h.
Referenced by setStatus().
statusStr() [1/2]
static std::string EchoLink::StationData::statusStr (Status status) static
Translate a status code to a string.
Parameters
status The status code to translate
Returns
Returns the string representation of the given status code
statusStr() [2/2]
std::string EchoLink::StationData::statusStr (void) const inline
Return the string representation of the status.
Returns
Returns a string representation of the status
Definition at line 191 of file EchoLinkStationData.h.
References statusStr().
Referenced by EchoLink::Directory::statusStr(), and statusStr().
time()
const std::string & EchoLink::StationData::time (void) const inline
Get the time.
Returns
Returns the time
Definition at line 203 of file EchoLinkStationData.h.
Referenced by setTime().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const StationData & station) friend
Output stream operator.
Parameters
os The stream to output data to
station The station data to output to the stream
Member Data Documentation
MAXCALL
const int EchoLink::StationData::MAXCALL = 15 static
The maximum length of a callsign.
Definition at line 122 of file EchoLinkStationData.h.
MAXDATA
const int EchoLink::StationData::MAXDATA = 45 static
The maximum length of the data field.
Definition at line 123 of file EchoLinkStationData.h.
MAXDESC
const int EchoLink::StationData::MAXDESC = 27 static
The maximum length of a description.
Definition at line 124 of file EchoLinkStationData.h.
MAXID
const int EchoLink::StationData::MAXID = 7 static
The maximum length of the id field.
Definition at line 125 of file EchoLinkStationData.h.
MAXIP
const int EchoLink::StationData::MAXIP = 20 static
The maximum length of the ip address.
Definition at line 126 of file EchoLinkStationData.h.
The documentation for this class was generated from the following file:
EchoLinkStationData.h