<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<HTML>

<HEAD>
  <META http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
  <LINK REL=STYLESHEET TYPE="text/css"
        HREF="stylesheet" TITLE="Basic Styling">
  <TITLE>SvxLink - a Multi Purpose Voice Services System</TITLE>
</HEAD>

<BODY>
<H1 align="center">SvxLink - Multi Purpose Voice Services System</H1>
<HR noshade/>
<TABLE width="100%" border="0" cellspacing="20">
  <COLGROUP>
    <COL width="0*">
    <COL>
  </COLGROUP>
  <TR valign="top"><TD NOWRAP align="right">
    <A href="index.php">Main Screen</A><BR/>
    <A href="news.php">Project News</A><BR/>
    <A href="screenshots.php">Screenshots</A><BR/>
    <A href="install.php">Installation Instructions</A><BR/>
    <A href="qtel_usage.php">Qtel User Docs</A><BR/>
    <A href="svxlink_usage.php">SvxLink Server User Docs</A><BR/>
    <A href="moreinfo.php">Developer Documentation</A><BR/>
    <A
    href="https://sourceforge.net/project/showfiles.php?group_id=84813">
      Software Downloads</A><BR/>
    <A href="https://sourceforge.net/projects/svxlink/">SourceForge Summary</A>
  </TD>
  <TD>
  

