.TH MODULEHELP.CONF 5 "MAY 2011" Linux "File Formats"
.
.SH NAME
.
ModuleHelp.conf \- Configuration file for the SvxLink server Help module
.
.SH DESCRIPTION
.
.B open-link
is a general purpose voice service system for ham radio use. This man-page
describe the SvxLink server configuration for the Help module.
.P
The Help module implements a simple help system.
.
.SH CONFIGURATION VARIABLES
.
There are a couple of configuration variables that are common to all modules.
The documentation for these can be found in the
.BR open-link.conf (5)
manual page.
.P
The Help module does not have any module specific configuration variables.
.
.SH FILES
.
.TP
.IR /etc/open-link/open-link.conf " (or deprecated " /etc/open-link.conf ")"
The system wide configuration file.
.TP
.IR ~/.open-link/open-link.conf
Per user configuration file.
.TP
.I /etc/open-link/open-link.d/ModuleHelp.conf
Global modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.TP
.I ~/.open-link/open-link.d/ModuleHelp.conf
Per user modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.
.SH AUTHOR
.
Tobias Blomberg (SM0SVX) <sm0svx at users dot sourceforge dot net>
.
.SH "SEE ALSO"
.
.BR open-link.conf (5)
