.TH MODULETCLVOICEMAIL.CONF 5 "MAY 2011" Linux "File Formats"
.
.SH NAME
.
ModuleTclVoiceMail.conf \- Configuration file for the SvxLink server
TclVoiceMail module
.
.SH DESCRIPTION
.
.B open-link
is a general purpose voice service system for ham radio use. This man-page
describe the SvxLink server configuration for the TclVoiceMail module.
.P
The TclVoiceMail module implements a simple voice mail system.
.
.SH CONFIGURATION VARIABLES
.
There are a couple of configuration variables that are common to all modules.
The documentation for these can be found in the
.BR open-link.conf (5)
manual page.
.P
The TclVoiceMail module does not have any module specific configuration
variables. It is configured in another configuration file. Its default location
is /etc/open-link/TclVoiceMail.conf. The configuration file is also looked for in
directory "$HOME/.open-link/". The comments in that file should be enough to
understand how to configure the voice mail module. 
.
.SH FILES
.
.TP
.IR /etc/open-link/open-link.conf " (or deprecated " /etc/open-link.conf ")"
The system wide configuration file.
.TP
.IR ~/.open-link/open-link.conf
Per user configuration file.
.TP
.I /etc/open-link/open-link.d/ModuleTclVoiceMail.conf
Global modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.TP
.I ~/.open-link/open-link.d/ModuleTclVoiceMail.conf
Per user modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.TP
.I /etc/open-link/TclVoiceMail.conf
System wide configuration file for the TclVoiceMail module.
.TP
.I ~/.open-link/TclVoiceMail.conf
Per user configuration file for the TclVoiceMail module.
.TP
.I /var/spool/open-link/voice_mail
Spool directory for voice mails.
.
.SH AUTHOR
.
Tobias Blomberg (SM0SVX) <sm0svx at users dot sourceforge dot net>
.
.SH "SEE ALSO"
.
.BR open-link.conf (5)
