.TH MODULEECHOLINK.CONF 5 "MAY 2011" Linux "File Formats"
.
.SH NAME
.
ModuleEchoLink.conf \- Configuration file for the SvxLink server EchoLink module
.
.SH DESCRIPTION
.
.B svxlink
is a general purpose voice service system for ham radio use. This man-page
describe the SvxLink server configuration for the EchoLink module.
.P
The EchoLink module is used to connect to other EchoLink stations.
.
.SH CONFIGURATION VARIABLES
.
There are a couple of configuration variables that are common to all modules.
The documentation for these can be found in the
.BR svxlink.conf (5)
manual page.
.P
Here is the description of all module specific configuration
variables that the SvxLink EchoLink module understands.
.
.SS ModuleEchoLink
.
.TP
.B ALLOW_IP
Use this variable very carefully. Connections originating from the given subnet
will not be checked against the EchoLink directory server. A typical use of this
is if you want to connect to your own svxlink server and both the server and you
are behind a IP masquerading firewall. 
.TP
.B DROP_INCOMING
Drop all incoming connections where the remote callsign match this regular
expression. No message will be sent to the remote station notifying about the
drop. The connection will just be ignored.
For more information on the syntax, see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B REJECT_INCOMING
Reject all incoming connections where the remote callsign match this regular
expression. A message will be sent to the remote station indicating that the
connection was rejected.
The DROP_INCOMING directive will be evaluated before REJECT_INCOMING.
For more information on the syntax, see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B ACCEPT_INCOMING
Only accept incoming connections where the remote callsign match this regular
expression. If the callsign doesn't match, a message will be sent to the
remote station indicating that the connection was rejected.
The DROP_INCOMING and REJECT_INCOMING directives will be evaluated before
ACCEPT_INCOMING.
For more information on the syntax, see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B REJECT_OUTGOING
Reject all outgoing connections where the remote callsign match this regular
expression. For more information on the syntax, see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B ACCEPT_OUTGOING
Only accept outgoing connections where the remote callsign match this regular
expression. The REJECT_OUTGOING directive will be evaluated before
ACCEPT_OUTGOING. For more information on the syntax, see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B SERVER
The IP address or name of the EchoLink directory server to use. 
.TP
.B CALLSIGN
The callsign to use to login to the EchoLink directory server. 
.TP
.B SYSOPNAME
The name of the person or club that is responsible for this system. 
.TP
.B PASSWORD
The EchoLink directory server password to use. 
.TP
.B LOCATION
The location of the station. Note: In the default configuration file the value
of this configuration variable starts with "[Svx]". This is of course not
necessary but it's fun to see which other stations are running SvxLink. 
.TP
.B MAX_QSOS
The maximum number of stations that can participate in a conference QSO on this
node. If more stations try to connect, the connect request will be rejected. 
.TP
.B MAX_CONNECTIONS
When more stations than specified in MAX_QSOS try to connect, a connection will
temporarily be established long enough to play a message telling the remote
station that the connection was rejected. The connection is then immediately
terminated. If the number of connections exceeds MAX_CONNECTIONS, the connect
request is just ignored. This variable is typically set to MAX_QSOS+1 or more if
using a large number for MAX_QSOS. 
.TP
.B LINK_IDLE_TIMEOUT
The number of seconds that a connection is idle before disconnection will occur.
This is to prevent a link to stay open if someone forget to disconnect. Disable
this feature by setting this config variable to zero (or comment it out). 
.TP
.B DESCRIPTION
A longer description that is sent to remote stations upon connection. This
description should typically include detailed station information like QTH,
transceiver frequency/power, antenna, CTCSS tone frequency etc.
.
.SH REGULAR EXPRESSIONS
.
Regular expressions are used in the DROP, REJECT and ACCEPT configuration
variables. A regular expression can be quite complex and the syntax is
fully described in the
.BR regex (7)
manual page. This is just a quick tutorial for the most important features.
.TP
.B ^
match the beginning of a string.
.TP
.B $
match the end of a string.
.TP
.B .
match one character.
.TP
.B *
match the previous expression zero or more times.
.TP
.B |
match the expression before OR after the |.
.TP
.B \\\\
escape the following character. Note that backslash is also parsed by the
SvxLink configuration parser so a backslash must actually be typed as two.
For example to include a * in the matching pattern it must be escaped as
\\\\*.
.TP
.B ()
grouping an expression.
.TP
.B []
match any of the characters inside of the brackets.
.P
Some examples:
.TP
.B ^(AB1CDE|BA5CBA-L)$
Match AB1CDE or BA5CBA-L.
.TP
.B ^(AB1CDE-[LR])$
Match AB1CDE-L or AB1CDR-R.
.TP
.B ^(AB1.*)$
Match all callsigns starting with AB1.
.TP
.B ^(\\\\\\\\*.*\\\\\\\\*)$
Match all conference "callsigns". We need to escape the star character since
it would otherwise be parsed by the regular expression parser. We also need
two backslah characters so that the SvxLink configuration reader doesn't
parse it as an escape sequence.
.P
The matches in SvxLink are case insensitive so "sm3" and "SM3" are the same.
SvxLink use extended regular expressions (see
.BR regex (7)
). You almost always want to start the regular expression with "^(" and end
it with ")$" so that the whole callsign will be used in the match.
.
.SH FILES
.
.TP
.IR /etc/svxlink/svxlink.conf " (or deprecated " /etc/svxlink.conf ")"
The system wide configuration file.
.TP
.IR ~/.svxlink/svxlink.conf
Per user configuration file.
.TP
.I /etc/svxlink/svxlink.d/ModuleEchoLink.conf
Global modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.TP
.I ~/.svxlink/svxlink.d/ModuleEchoLink.conf
Per user modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.
.SH AUTHOR
.
Tobias Blomberg (SM0SVX) <sm0svx at users dot sourceforge dot net>
.
.SH "SEE ALSO"
.
.BR svxlink.conf (5)
