.TH MODULEECHOLINK.CONF 5 "APRIL 2009" Linux "File Formats"
.
.SH NAME
.
ModuleEchoLink.conf \- Configuration file for the SvxLink server EchoLink module
.
.SH DESCRIPTION
.
.B svxlink
is a general purpose voice service system for ham radio use. This man-page
describe the SvxLink server configuration for the EchoLink module.
.P
The EchoLink module is used to connect to other EchoLink stations.
.
.SH CONFIGURATION VARIABLES
.
There are a couple of configuration variables that are common to all modules.
The documentation for these can be found in the
.BR svxlink.conf (5)
manual page.
.P
Here is the description of all module specific configuration
variables that the SvxLink EchoLink module understands.
.
.SS ModuleEchoLink
.
.TP
.B ALLOW_IP
Use this variable very carefully. Connections originating from the given subnet
will not be checked against the EchoLink directory server. A typical use of this
is if you want to connect to your own svxlink server and both the server and you
are behind a IP masquerading firewall. 
.TP
.B DROP
Drop all connections where the remote callsign match this regular expression.
No message will be sent to the remote station notifying about the drop. The
connection will just be ignored.
For more information see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B REJECT
Reject all connections where the remote callsign match this regular expression.
A message will be sent to the remote station indicating that the connection was
rejected.
The DROP directive will be evaluated before REJECT.
For more information see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B ACCEPT
Only accept connections where the remote callsign match this regular expression.
If the callsign doesn't match, a message will be sent to the remote station
indicating that the connection was rejected.
The DROP and REJECT directives will be evaluated before ACCEPT.
For more information see the
.B REGULAR EXPRESSIONS
chapter below.
.TP
.B SERVER
The IP address or name of the EchoLink directory server to use. 
.TP
.B CALLSIGN
The callsign to use to login to the EchoLink directory server. 
.TP
.B SYSOPNAME
The name of the person or club that is responsible for this system. 
.TP
.B PASSWORD
The EchoLink directory server password to use. 
.TP
.B LOCATION
The location of the station. Note: In the default configuration file the value
of this configuration variable starts with "[Svx]". This is of course not
necessary but it's fun to see which other stations are running SvxLink. 
.TP
.B LOCATION_INFO
Enter the section name that contains information required for transfering
positioning data to location servers. Setting this item makes the system
visible on the EchoLink link status page and the APRS network.
.TP
.B MAX_QSOS
The maximum number of stations that can participate in a conference QSO on this
node. If more stations try to connect, the connect request will be rejected. 
.TP
.B MAX_CONNECTIONS
When more stations than specified in MAX_QSOS try to connect, a connection will
temporarily be established long enough to play a message telling the remote
station that the connection was rejected. The connection is then immediately
terminated. If the number of connections exceeds MAX_CONNECTIONS, the connect
request is just ignored. This variable is typically set to MAX_QSOS+1 or more if
using a large number for MAX_QSOS. 
.TP
.B LINK_IDLE_TIMEOUT
The number of seconds that a connection is idle before disconnection will occur.
This is to prevent a link to stay open if someone forget to disconnect. Disable
this feature by setting this config variable to zero (or comment it out). 
.TP
.B DESCRIPTION
A longer description that is sent to remote stations upon connection. This
description should typically include detailed station information like QTH,
transceiver frequency/power, antenna, CTCSS tone frequency etc.
.
.SS LocationInfo
.
.TP
.B STATUS_SERVER_LIST
Enter a space separated list of EchoLink status servers that should be used
to send node status beacons. Your node information can be found
on http://www.echolink.org/links.jsp.
The format is host:port. Host - hostname or IP address, port - UDP port.
Don't change the default unless you know what you are doing. If you don't
want to update the EchoLink status server, comment out this configuration
variable.

Example:
.br
STATUS_SERVER_LIST=aprs.echolink.org:5199
.TP
.B APRS_SERVER_LIST
This configuration variable specifies connection parameters for connecting
to an APRS server network using the TCP protocol. In this case, the positioning
information is forwarded to the worldwide APRS network. Have a look at
http://aprs.fi/.

To choose a suitable APRS server from the so called tier 2 network, have a
look at http://www.aprs2.net/. Either choose a specific server or one of the
regional addresses. The regional addresses bundle all APRS servers within a
region so that a random tier 2 server is chosen within the region. There are
five regions defined: noam.aprs2.net - North America, euro.aprs2.net - Europe,
asia.aprs2.net - Asia, soam.aprs2.net - South America and Africa,
aunz.aprs2.net - Austrailia and New Zeeland.
The format is a space separated list of host:port entries. Host - hostname
or IP address, port - TCP port.

Example:
.br
APRS_SERVER_LIST=euro.aprs2.net:14580
.TP
.B LON_POSITION
The longitude of the station position, entered as "degrees.arcminutes.arcseconds"

Example:
.br
LON_POSITION=09.02.20E
.TP
.B LAT_POSITION
The latitude of the station position, entered as "degrees.arcminutes.arcseconds"

Example:
.br
LAT_POSITION=51.02.22N
.TP
.B FREQUENCY
The tx-frequency of the link/repeater in MHz. For repeaters, information about
the RX/TX shift in the COMMENT configuration variable may be useful.

Example:
.br
FREQUENCY=430.050     # tx-frequency is 430.050 MHz
.TP
.B TX_POWER
The power of your transmitter in watts.

Example:
.br
TX_POWER=10           # tx output is 10 watts
.TP
.B ANTENNA_GAIN
The gain of your antenna in dBd.

Example:
.br
ANTENNA_GAIN=5        # antenna gain is 5 dBd
.TP
.B ANTENNA_HEIGHT
The height of the link-/repeater antenna in meters or feet above the terrain, 
not sealevel.

Example:
.br
ANTENNA_HEIGHT=10m    # 10 meters above the ground
.br
ANTENNA_HEIGHT=90     # 90 feet
.TP
.B ANTENNA_DIR
Main beam direction of the antenna in degrees. If an omni direction antenna is
used, specify -1 as the direction.

Example:
.br
ANTENNA_DIR=-1        # an omni directional antenna is used
.br
ANTENNA_DIR=128       # main beam direction is 128 degrees
.TP
.B PATH
The PATH variable controls the way of forwarding your beacon inside the APRS 
network if it is gated by a local APRS digipeater. In some cases it has to be 
changed according to local requirements. Please contact your local APRS sysop
for further information. Changes should be made only according to the NEWn-N 
paradigm. Leave this variable untouched if you are unsure of its setting.
No spaces or control characters are allowed. PATH has no influence on the 
propagation on non-RF networks.

Examples:
.br
PATH=WIDE1-1
.br
PATH=WIDE1-1,WIDE2-2
.TP
.B BEACON_INTERVAL
The interval, in minutes, with which beacons will be sent to the APRS network.
A good value is 10 minutes. If your beacon is gated via RF, please increase 
the interval a bit to keep the APRS traffic on RF produced by the APRS RF gate
as low as possible. Intervals shorter than 10 minutes will be changed to 10.

Example:
.br
BEACON_INTERVAL=30    # APRS-beacons will be sent every 30 minutes.
.TP
.B TONE
The CTCSS subaudible tone that is to be used for operation over your link or
repeater. If you don't use tone control set it to 0.

Examples:
.br
TONE=136      # we are using a CTCSS-tone of 136.5 Hz
.br
TONE=0        # we don't use CTCSS subaudible or call tones
.br
TONE=1750     # the link/repeater use a tone burst of 1750 Hz
.TP
.B COMMENT
Specify a short comment here, maybe a link to your website 
or information that could be interesting for others. The length should not 
exceed 255 characters and may not have control characters like "Carriage Return"
(\\r) or "Line Feed" (\\n) inside. Make your comment as short as you can to
give users with a small display (TH-D7) the chance to display the full comment
text.

Example:
.br
COMMENT=[svx] Running SvxLink by SM0SVX
.
.SH REGULAR EXPRESSIONS
.
Regular expressions are used in the DROP, REJECT and ACCEPT configuration
variables. A regular expression can be quite complex and the syntax is
fully described in the
.BR regex (7)
manual page. This is just a quick tutorial for the most important features.
.TP
.B ^
match the beginning of a string.
.TP
.B $
match the end of a string.
.TP
.B .
match one character.
.TP
.B *
match the previous expression zero or more times.
.TP
.B |
match the expression before OR after the |.
.TP
.B \\\\
escape the following character. Note that backslash is also parsed by the
SvxLink configuration parser so a backslash must actually be typed as two.
For example to include a * in the matching pattern it must be escaped as
\\\\*.
.TP
.B ()
grouping an expression.
.TP
.B []
match any of the characters inside of the brackets.
.P
Some examples:
.TP
.B ^(AB1CDE|BA5CBA-L)$
Match AB1CDE or BA5CBA-L.
.TP
.B ^(AB1CDE-[LR])$
Match AB1CDE-L or AB1CDR-R.
.TP
.B ^(AB1.*)$
Match all callsigns starting with AB1.
.TP
.B ^(\\\\\\\\*.*\\\\\\\\*)$
Match all conference "callsigns". We need to escape the star character since
it would otherwise be parsed by the regular expression parser. We also need
two backslah characters so that the SvxLink configuration reader doesn't
parse it as an escape sequence.
.P
The matches in SvxLink are case insensitive so "sm3" and "SM3" are the same.
SvxLink use extended regular expressions (see
.BR regex (7)
). You almost always want to start the regular expression with "^(" and end
it with ")$" so that the whole callsign will be used in the match.
.
.SH FILES
.
.TP
.I /etc/svxlink.conf
The system wide configuration file.
.TP
.IR ~/.svxlink/svxlink.conf " or " ~/.svxlinkrc
Per user configuration file.
.TP
.I /etc/svxlink.d/ModuleEchoLink.conf
Global modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.TP
.I ~/.svxlink/svxlink.d/ModuleEchoLink.conf
Per user modularized configuration file. Depends on the CFG_DIR configuration
variable setting.
.
.SH AUTHOR
.
Tobias Blomberg (SM0SVX) <sm0svx at users dot sourceforge dot net>
.
.SH "SEE ALSO"
.
.BR svxlink.conf (5)
