= Docker Image for SvxLink

The files in this directory are used to build and run SvxLink and all
associated utilities in a Docker image.

== Building the Image
The image is built using a script. This is a two step process where the first
step is to create a builder image from which the end product is a tar archive
containing the finished build. The second step is to build a runtime image from
the tar archive built in the previous step.

Configuring the build is done using environment variables. The following
variable are available.

IMG_NAME::
The name of the final image (Default: svxlink).

IMG_TAG::
The tag to use for the final image (Default: latest).

NUM_CORES::
The number of threads to use when building the source code. The default is
calculated dynamically depending on the number of cores available in the build
computer.

GIT_REPO::
Set this environment variable to the SvxLink Git repository you want to use
(Default: https://github.com/sm0svx/svxlink.git).

GIT_REF::
Set this environment variable to the Git ref (e.g. branch or tag) that you want
to use (Default: master).

RTLSDR_REPO::
The Git repo to use to download the source code for the rtl-sdr library
(Default: git://git.osmocom.org/rtl-sdr.git).

The final image is simply built by running the following script.

  ./build.sh


== Running the Image
Running the image is most easily done using the script below. It will create
two directories, conf and spool, in the current working directory. These
directories will contain the SvxLink configuration and spooled files,
respectively. After running the start script once the conf directory will
contain a set of default configuration files. Edit them to your liking and
restart the container.

Starting the svlink container can be done using the following command. It will
get you a prompt from where to run all SvxLink utilities.

  ./run.sh

It is also possible to directly run a utility by giving all arguments on the
command line. In that case, the container will be put into the background.

  ./run.sh svxlink

For a backgrounded container the log is accessed using the following command.

  sudo docker logs -f svxlink

Stop and delete the container using the following command.

  sudo docker rm -f svxlink

