= SvxLink release 26.05.2 -- 09 Oct 2026

This is a SECURITY bugfix release for the 26.05 release. Several security
related bugs have been fixed. Have a look at the ChangeLogs below for an
overview of all fixes.

In depth description of each security patch can be found at the
https://github.com/sm0svx/svxlink/security/advisories?state=published[GitHub Security Advisories page].

'''

== Complete ChangeLog for SvxLink Server version 1.10.2

* Security: ModuleMetarInfo: malformed METAR report → uncaught
  std::out_of_range crash and 100% CPU infinite-loop hang (remote)
  (GHSA-m4q5-8r78-5gqg)
  Credit: Mark Rose <markrose@markrose.ca>

* Security: SvxReflector: Use-after-free / iterator invalidation in
  Reflector::broadcastMsg when a client is disconnected due to a write
  failure (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu

* Security: LocationInfo: Stack buffer overflow via unbounded sprintf in
  APRS UDP status reporting (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu

* ModuleMetarInfo: The libcurl handle was not removed from the multi
  handle before being cleaned up (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu

* ModuleEchoLink: The PTY object was not deleted on module cleanup
  (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu


== Complete ChangeLog for Qtel version 1.3.0

No changes in this release.


== Complete ChangeLog for EchoLib version 1.3.8

* Security: EchoLink Qso: unvalidated non-audio (NDATA) packet length →
  out-of-bounds read and std::string invalid-range crash (network)
  (GHSA-2m63-p9h9-p5rf)
  Credit: Mark Rose <markrose@markrose.ca>

* Security: EchoLink: Remote callsign received in SDES packets not
  sanitized, which could lead to TCL command injection in SvxLink and
  buffer overflows (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu

* Security: EchoLink proxy: Missing bounds check when buffering
  unprocessed TCP data could overflow the receive buffer
  (GHSA-6w9x-486p-ggrj)
  Credit: mark-mcu


== Complete ChangeLog for the Async library version 1.9.1

No changes in this release.
