Async: Async::MsgPacker< std::map< Tag, Value > > Class Template Reference
Async::MsgPacker< std::map< Tag, Value > > Class Template Reference
#include <AsyncMsg.h>
Static Public Member Functions
static bool pack (std::ostream &os, const std::map< Tag, Value > &m)
static size_t packedSize (const std::map< Tag, Value > &m)
static bool unpack (std::istream &is, std::map< Tag, Value > &m)
Detailed Description
template<typename Tag, typename Value>
class Async::MsgPacker< std::map< Tag, Value > >
Definition at line 497 of file AsyncMsg.h.
Member Function Documentation
template<typename Tag , typename Value > static bool Async::MsgPacker< std::map< Tag, Value > >::pack (std::ostream & os, const std::map< Tag, Value > & m) inline static
Definition at line 500 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename Tag , typename Value > static size_t Async::MsgPacker< std::map< Tag, Value > >::packedSize (const std::map< Tag, Value > & m) inline static
Definition at line 517 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename Tag , typename Value > static bool Async::MsgPacker< std::map< Tag, Value > >::unpack (std::istream & is, std::map< Tag, Value > & m) inline static
Definition at line 528 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
The documentation for this class was generated from the following file:
AsyncMsg.h