Async: Async::TcpServerBase Class Reference
Async::TcpServerBase Class Reference abstract
The base class for creating a TCP server.
#include <AsyncTcpServerBase.h>
Public Member Functions
TcpServerBase (const std::string &port_str, const Async::IpAddress &bind_ip)
Default constuctor.
virtual ~TcpServerBase (void)
Destructor.
int numberOfClients (void)
Get the number of clients that is connected to the server.
TcpConnection * getClient (unsigned int index)
Get the client object pointer from the server.
int writeAll (const void *buf, int count)
Write data to all connected clients.
int writeOnly (TcpConnection *con, const void *buf, int count)
Send data only to the given client.
int writeExcept (TcpConnection *con, const void *buf, int count)
Send data to all connected clients except the given client.
Protected Member Functions
virtual void createConnection (int sock, const IpAddress &remote_addr, uint16_t remote_port)=0
void addConnection (TcpConnection *con)
void removeConnection (TcpConnection *con)
Detailed Description
The base class for creating a TCP server.
Author
Tobias Blomberg
Date
2003-12-07
Definition at line 112 of file AsyncTcpServerBase.h.
Constructor & Destructor Documentation
Async::TcpServerBase::TcpServerBase (const std::string & port_str, const Async::IpAddress & bind_ip)
Default constuctor.
Parameters
port_str A port number or service name to listen to
bind_ip The IP to bind the server to
virtual Async::TcpServerBase::~TcpServerBase (void) virtual
Destructor.
Member Function Documentation
void Async::TcpServerBase::addConnection (TcpConnection * con) protected
Referenced by Async::TcpServer< ConT >::createConnection().
virtual void Async::TcpServerBase::createConnection (int sock, const IpAddress & remote_addr, uint16_t remote_port) protected pure virtual
Implemented in Async::TcpServer< ConT >.
TcpConnection* Async::TcpServerBase::getClient (unsigned int index)
Get the client object pointer from the server.
Parameters
index The wanted client by number 0 - numberOfClients()-1
Returns
The TcpConnection pointer to the client (zero if not found)
Referenced by Async::TcpServer< ConT >::getClient().
int Async::TcpServerBase::numberOfClients (void)
Get the number of clients that is connected to the server.
Returns
The number of connected clients
void Async::TcpServerBase::removeConnection (TcpConnection * con) protected
Referenced by Async::TcpServer< ConT >::createConnection().
int Async::TcpServerBase::writeAll (const void * buf, int count)
Write data to all connected clients.
Parameters
buf The data buffer
count The number of bytes in the data buffer
Returns
The number of bytes sent
int Async::TcpServerBase::writeExcept (TcpConnection * con, const void * buf, int count)
Send data to all connected clients except the given client.
Parameters
con The TcpConnection object not to send to
buf The data buffer
count The number of bytes in the data buffer
Returns
The number of bytes sent
int Async::TcpServerBase::writeOnly (TcpConnection * con, const void * buf, int count)
Send data only to the given client.
Parameters
con The TcpConnection object to send to
buf The data buffer
count The number of bytes in data buffer
Returns
The number of bytes sent
The documentation for this class was generated from the following file:
AsyncTcpServerBase.h