Async: Async::DnsResourceRecordCNAME Class Reference
Async::DnsResourceRecordCNAME Class Reference
A class for representing a CNAME DNS resource record.
#include <AsyncDnsResourceRecord.h>
Public Types
using CName = std::string
Public Types inherited from Async::DnsResourceRecordCRTP< DnsResourceRecordCNAME >
using List
The type for a list of resource records.
Public Types inherited from Async::DnsResourceRecord
enum class Type {
ANY , A , PTR , CNAME ,
SRV , A , PTR , CNAME ,
SRV
}
The record type.
enum class Class { IN , IN }
The record class.
enum class Type {
ANY , A , PTR , CNAME ,
SRV , A , PTR , CNAME ,
SRV
}
enum class Class { IN , IN }
using Name = std::string
using Ttl = uint32_t
using List = std::vector<std::unique_ptr<DnsResourceRecord>>
The type for a list of resource records.
Public Member Functions
DnsResourceRecordCNAME (const Name &name, Ttl ttl, const CName &cname="")
Constructor.
virtual bool operator== (const DnsResourceRecordCNAME &other) const
Equality comparison operator.
virtual std::string toString (void) const
The string representation of this record.
void setName (const CName &cname)
Set the FQDN for this record.
const CName & cname (void) const
The FQDN for this record.
DnsResourceRecordCNAME (const std::string &name, uint32_t ttl, const std::string &cname="")
~DnsResourceRecordCNAME (void)
virtual const Type type (void) const
The type of record.
virtual std::string toString (void) const
The string representation of this record.
void setName (const std::string &cname)
const std::string & cname (void) const
Public Member Functions inherited from Async::DnsResourceRecordCRTP< DnsResourceRecordCNAME >
DnsResourceRecordCRTP (const Name &name, Ttl ttl)
Constructor.
virtual DnsResourceRecord * clone (void) const
Clone this class.
virtual bool operator== (const DnsResourceRecord &other) const
Equality comparison operator.
Public Member Functions inherited from Async::DnsResourceRecord
DnsResourceRecord (const Name &name, Ttl ttl)
Constructor.
virtual ~DnsResourceRecord (void)
Destructor.
Class classId (void) const
The DNS class for the record.
const char * classStr (void) const
The DNS class for the record as a string.
const std::string & typeStr (void) const
The type of record as a string.
void setName (const Name &name)
Set the name for this record.
const Name & name (void) const
The name of this record.
void setTtl (Ttl ttl)
Set the TTL for this record.
Ttl ttl (void) const
The TTL for this record.
DnsResourceRecord (const std::string &name, uint32_t ttl)
Default constructor.
DnsResourceRecord (const DnsResourceRecord &)=delete
Disallow copy construction.
DnsResourceRecord & operator= (const DnsResourceRecord &)=delete
Disallow copy assignment.
virtual ~DnsResourceRecord (void)
Destructor.
Class classId (void) const
A_brief_member_function_description.
const char * classStr (void) const
const std::string & typeStr (void) const
void setName (const std::string &name)
const std::string & name (void) const
void setTtl (uint32_t ttl)
uint32_t ttl (void) const
Static Public Member Functions
static const Type staticType (void)
The type for this specific class.
static const Type staticType (void)
Static Public Member Functions inherited from Async::DnsResourceRecord
static const Type staticType (void)
The type for this specific class.
static const std::string & typeToString (Type type)
The type for this specific class represented as a string.
static const std::string & typeToString (Type type)
Additional Inherited Members
Static Public Attributes inherited from Async::DnsResourceRecord
static constexpr Ttl MAX_TTL = 0x7fffffff
The maximum allowed value for a TTL.
Detailed Description
A class for representing a CNAME DNS resource record.
Author
Tobias Blomberg / SM0SVX
Date
2021-05-22
This class represents a CNAME DNS resource record. One or more resource records is the result of performing a DNS query. This specific resource record maps a hostname to other hostnames.
#include <iostream>
#include <AsyncCppApplication.h>
#include <AsyncDnsLookup.h>
using namespace Async;
class MyClass : public sigc::trackable
{
  public:
    MyClass(void)
    {
      dns.resultsReady.connect(mem_fun(*this, &MyClass::onResultsReady));
      dns.lookup("www.svxlink.org");
      //dns.lookup("www.svxlink.org", DnsLookup::Type::CNAME);
      //dns.lookup("185.199.110.153");
      //dns.lookup("185.199.110.153", DnsLookup::Type::PTR);
      //dns.lookup("153.110.199.185.in-addr.arpa.", DnsLookup::Type::PTR);
      //std::string srv = "_svxreflector._tcp.test.svxlink.org";
      //dns.addStaticResourceRecord(
      //    new DnsResourceRecordSRV(srv, 3600, 15, 10, 5304, "localhost."));
      //dns.lookup(srv, DnsLookup::Type::SRV);
      std::cout << "Starting " << dns.typeStr() << " record query for \""
                << dns.label() << "\"..." << std::endl;
    }
    void onResultsReady(DnsLookup& dns)
    {
      if (!dns.lookupFailed())
      {
          // Simple IP address lookup API
        std::cout << "IP addresses received:\n";
        for (auto& addr : dns.addresses())
        {
          std::cout << addr << std::endl;
        }
        std::cout << std::endl;
          // Access to all resource records
        std::cout << "All resource records received:\n";
        for (auto& rr : dns.resourceRecords())
        {
          std::cout << rr->toString() << std::endl;
        }
        std::cout << std::endl;
          // Access A records with full detail
        DnsResourceRecordA::List a_rrs;
        dns.resourceRecords(a_rrs);
        if (!a_rrs.empty())
        {
          std::cout << "A records received:\n";
          for (auto& rr : a_rrs)
          {
            std::cout << rr->name() << "\t" << rr->ttl() << "\t" << rr->ip()
                      << std::endl;
          }
          std::cout << std::endl;
        }
          // Access PTR records with full detail
        DnsResourceRecordPTR::List ptr_rrs;
        dns.resourceRecords(ptr_rrs);
        if (!ptr_rrs.empty())
        {
          std::cout << "PTR records received:\n";
          for (auto& rr : ptr_rrs)
          {
            std::cout << rr->name() << "\t" << rr->ttl() << "\t" << rr->dname()
                      << std::endl;
          }
          std::cout << std::endl;
        }
          // Access CNAME records with full detail
        DnsResourceRecordCNAME::List cname_rrs;
        dns.resourceRecords(cname_rrs);
        if (!cname_rrs.empty())
        {
          std::cout << "CNAME records received:\n";
          for (auto& rr : cname_rrs)
          {
            std::cout << rr->name() << "\t" << rr->ttl() << "\t" << rr->cname()
                      << std::endl;
          }
          std::cout << std::endl;
        }
          // Access SRV records with full detail
        DnsResourceRecordSRV::List srv_rrs;
        dns.resourceRecords(srv_rrs);
        if (!srv_rrs.empty())
        {
          std::cout << "SRV records received:\n";
          for (auto& rr : srv_rrs)
          {
            std::cout << rr->name() << "\t" << rr->ttl() << "\t" << rr->prio()
                      << " " << rr->weight() << " " << rr->port() << " "
                      << rr->target() << std::endl;
          }
        }
      }
      else
      {
        std::cout << "*** ERROR: The " << dns.typeStr()
                  << " record DNS lookup for " << dns.label()
                  << " failed" << std::endl;
      }
      Application::app().quit();
    }
  private:
    DnsLookup dns;
};
int main(int argc, char **argv)
{
  CppApplication app;
  MyClass dns;
  app.exec();
}
Definition at line 249 of file AsyncResourceRecord.h.
Member Typedef Documentation
CName
using Async::DnsResourceRecordCNAME::CName = std::string
Definition at line 487 of file AsyncDnsResourceRecord.h.
Constructor & Destructor Documentation
DnsResourceRecordCNAME() [1/2]
Async::DnsResourceRecordCNAME::DnsResourceRecordCNAME (const Name & name, Ttl ttl, const CName & cname = "") inline
Constructor.
Parameters
name The name of this record
ttl The time-to-live, in seconds, for this record
cname The FQDN associaated with this record name
Definition at line 500 of file AsyncDnsResourceRecord.h.
DnsResourceRecordCNAME() [2/2]
Async::DnsResourceRecordCNAME::DnsResourceRecordCNAME (const std::string & name, uint32_t ttl, const std::string & cname = "") inline
Definition at line 254 of file AsyncResourceRecord.h.
~DnsResourceRecordCNAME()
Async::DnsResourceRecordCNAME::~DnsResourceRecordCNAME (void) inline
Definition at line 257 of file AsyncResourceRecord.h.
Member Function Documentation
cname() [1/2]
const CName & Async::DnsResourceRecordCNAME::cname (void) const inline
The FQDN for this record.
Returns
Return the FQDN for this record
Definition at line 538 of file AsyncDnsResourceRecord.h.
Referenced by operator==(), setName(), setName(), and toString().
cname() [2/2]
const std::string & Async::DnsResourceRecordCNAME::cname (void) const inline
Definition at line 268 of file AsyncResourceRecord.h.
operator==()
virtual bool Async::DnsResourceRecordCNAME::operator== (const DnsResourceRecordCNAME & other) const inline virtual
Equality comparison operator.
Parameters
other The other resource record to comapare to
Returns
Return true if the two records are equal
NOTE: The TTL is not used in the comparison.
Implements Async::DnsResourceRecordCRTP< DnsResourceRecordCNAME >.
Definition at line 511 of file AsyncDnsResourceRecord.h.
References cname(), and Async::DnsResourceRecord::operator==().
setName() [1/2]
void Async::DnsResourceRecordCNAME::setName (const CName & cname) inline
Set the FQDN for this record.
Parameters
cname The new FQDN for this record
Definition at line 532 of file AsyncDnsResourceRecord.h.
References cname().
setName() [2/2]
void Async::DnsResourceRecordCNAME::setName (const std::string & cname) inline
Definition at line 267 of file AsyncResourceRecord.h.
References cname().
staticType() [1/2]
static const Type Async::DnsResourceRecordCNAME::staticType (void) inline static
The type for this specific class.
Definition at line 492 of file AsyncDnsResourceRecord.h.
References Async::DnsResourceRecord::CNAME.
Referenced by type().
staticType() [2/2]
static const Type Async::DnsResourceRecordCNAME::staticType (void) inline static
Definition at line 252 of file AsyncResourceRecord.h.
References Async::DnsResourceRecord::CNAME.
toString() [1/2]
virtual std::string Async::DnsResourceRecordCNAME::toString (void) const inline virtual
The string representation of this record.
Returns
Return the string representation of this record
Reimplemented from Async::DnsResourceRecord.
Definition at line 521 of file AsyncDnsResourceRecord.h.
References cname(), and Async::DnsResourceRecord::toString().
toString() [2/2]
virtual std::string Async::DnsResourceRecordCNAME::toString (void) const inline virtual
The string representation of this record.
Returns
Return the string representation of this record
Reimplemented from Async::DnsResourceRecord.
Definition at line 260 of file AsyncResourceRecord.h.
References cname(), and Async::DnsResourceRecord::toString().
type()
virtual const Type Async::DnsResourceRecordCNAME::type (void) const inline virtual
The type of record.
Returns
Return the type of this record
Reimplemented from Async::DnsResourceRecordCRTP< DnsResourceRecordCNAME >.
Definition at line 259 of file AsyncResourceRecord.h.
References staticType().
The documentation for this class was generated from the following files:
AsyncDnsResourceRecord.h
AsyncResourceRecord.h