Async: Async::AudioDebugger Class Reference
Async::AudioDebugger Class Reference
This class is used to debug an audio stream.
#include <AsyncAudioDebugger.h>
Public Member Functions
AudioDebugger (Async::AudioSource *src=0)
Default constuctor.
virtual ~AudioDebugger (void)
Destructor.
void setName (std::string debug_name)
Set the name that is displayed before debug messages.
virtual int writeSamples (const float *samples, int count)
Write samples into this audio sink.
virtual void flushSamples (void)
Tell the sink to flush the previously written samples.
virtual void resumeOutput (void)
Resume audio output to the sink.
virtual void allSamplesFlushed (void)
The registered sink has flushed all samples.
Public Member Functions inherited from Async::AudioSink
AudioSink (void)
Default constuctor.
virtual ~AudioSink (void)
Destructor.
bool registerSource (AudioSource *source)
Register an audio source to provide samples to this sink.
void unregisterSource (void)
Unregister the previously registered audio source.
bool isRegistered (void) const
Check if an audio source has been registered.
AudioSource * source (void) const
Get the registered audio source.
Public Member Functions inherited from Async::AudioSource
AudioSource (void)
Default constuctor.
virtual ~AudioSource (void)
Destructor.
bool registerSink (AudioSink *sink, bool managed=false)
Register an audio sink to provide samples to.
void unregisterSink (void)
Unregister the previously registered audio sink.
bool isRegistered (void) const
Check if an audio sink has been registered.
AudioSink * sink (void) const
Get the registered audio sink.
bool sinkManaged (void) const
Check if the sink is managed or not.
void handleAllSamplesFlushed (void)
The registered sink has flushed all samples.
Additional Inherited Members
Protected Member Functions inherited from Async::AudioSink
void sourceResumeOutput (void)
Tell the source that we are ready to accept more samples.
void sourceAllSamplesFlushed (void)
Tell the source that all samples have been flushed.
bool setHandler (AudioSink *handler)
Setup another sink to handle the incoming audio.
void clearHandler (void)
Clear a handler that was previously setup with setHandler.
AudioSink * handler (void) const
Protected Member Functions inherited from Async::AudioSource
int sinkWriteSamples (const float *samples, int len)
void sinkFlushSamples (void)
bool setHandler (AudioSource *handler)
Setup another source to handle the outgoing audio.
AudioSource * handler (void) const
void clearHandler (void)
Clear a handler that was previously setup with setHandler.
Detailed Description
This class is used to debug an audio stream.
Author
Tobias Blomberg / SM0SVX
Date
2007-10-14
This class is used to debug an audio stream. It can be inserted in the flow and it will print out a debug message for each function call between the sink and the source.
Definition at line 119 of file AsyncAudioDebugger.h.
Constructor & Destructor Documentation
Async::AudioDebugger::AudioDebugger (Async::AudioSource * src = 0) inline
Default constuctor.
Definition at line 125 of file AsyncAudioDebugger.h.
References Async::AudioSource::registerSink(), Async::AudioSink::registerSource(), and Async::AudioSource::sink().
virtual Async::AudioDebugger::~AudioDebugger (void) inline virtual
Destructor.
Definition at line 144 of file AsyncAudioDebugger.h.
Member Function Documentation
virtual void Async::AudioDebugger::allSamplesFlushed (void) inline virtual
The registered sink has flushed all samples.
This function will be called when all samples have been flushed in the registered sink. This function is normally only called from a connected sink object.
Reimplemented from Async::AudioSource.
Definition at line 236 of file AsyncAudioDebugger.h.
References Async::AudioSink::sourceAllSamplesFlushed().
virtual void Async::AudioDebugger::flushSamples (void) inline virtual
Tell the sink to flush the previously written samples.
This function is used to tell the sink to flush previously written samples. When done flushing, the sink should call the sourceAllSamplesFlushed function. This function is normally only called from a connected source object.
Reimplemented from Async::AudioSink.
Definition at line 210 of file AsyncAudioDebugger.h.
References Async::AudioSource::sinkFlushSamples().
virtual void Async::AudioDebugger::resumeOutput (void) inline virtual
Resume audio output to the sink.
This function will be called when the registered audio sink is ready to accept more samples. This function is normally only called from a connected sink object.
Reimplemented from Async::AudioSource.
Definition at line 223 of file AsyncAudioDebugger.h.
References Async::AudioSink::sourceResumeOutput().
void Async::AudioDebugger::setName (std::string debug_name) inline
Set the name that is displayed before debug messages.
Parameters
debug_name The name to set
Definition at line 150 of file AsyncAudioDebugger.h.
virtual int Async::AudioDebugger::writeSamples (const float * samples, int count) inline virtual
Write samples into this audio sink.
Parameters
samples The buffer containing the samples
count The number of samples in the buffer
Returns
Returns the number of samples that has been taken care of
This function is used to write audio into this audio sink. If it returns 0, no more samples should be written until the resumeOutput function in the source have been called. This function is normally only called from a connected source object.
Reimplemented from Async::AudioSink.
Definition at line 163 of file AsyncAudioDebugger.h.
References Async::AudioSource::sinkWriteSamples().
The documentation for this class was generated from the following file:
AsyncAudioDebugger.h