Async: Async::Msg Class Reference
Async::Msg Class Reference
Base class for all messages.
#include <AsyncMsg.h>
Public Member Functions
virtual ~Msg (void)
bool packParent (std::ostream &) const
size_t packedSizeParent (void) const
bool unpackParent (std::istream &) const
virtual bool pack (std::ostream &) const
virtual size_t packedSize (void) const
virtual bool unpack (std::istream &) const
template<typename T >
bool pack (std::ostream &os, const T &val) const
template<typename T >
size_t packedSize (const T &val) const
template<typename T >
bool unpack (std::istream &is, T &val) const
template<typename T1 , typename T2 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2) const
template<typename T1 , typename T2 >
size_t packedSize (const T1 &v1, const T2 &v2) const
template<typename T1 , typename T2 >
bool unpack (std::istream &is, T1 &v1, T2 &v2)
template<typename T1 , typename T2 , typename T3 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3) const
template<typename T1 , typename T2 , typename T3 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3) const
template<typename T1 , typename T2 , typename T3 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3)
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4) const
template<typename T1 , typename T2 , typename T3 , typename T4 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4) const
template<typename T1 , typename T2 , typename T3 , typename T4 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5, T6 &v6)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5, T6 &v6, T7 &v7)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5, T6 &v6, T7 &v7, T8 &v8)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8, const T9 &v9) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8, const T9 &v9) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5, T6 &v6, T7 &v7, T8 &v8, T9 &v9)
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
bool pack (std::ostream &os, const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8, const T9 &v9, const T10 &v10) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
size_t packedSize (const T1 &v1, const T2 &v2, const T3 &v3, const T4 &v4, const T5 &v5, const T6 &v6, const T7 &v7, const T8 &v8, const T9 &v9, const T10 &v10) const
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 >
bool unpack (std::istream &is, T1 &v1, T2 &v2, T3 &v3, T4 &v4, T5 &v5, T6 &v6, T7 &v7, T8 &v8, T9 &v9, T10 &v10)
Detailed Description
Base class for all messages.
Author
Tobias Blomberg / SM0SVX
Date
2017-02-25
Examples:
AsyncMsg_demo.cpp.
Definition at line 556 of file AsyncMsg.h.
Constructor & Destructor Documentation
virtual Async::Msg::~Msg (void) inline virtual
Definition at line 559 of file AsyncMsg.h.
Member Function Documentation
virtual bool Async::Msg::pack (std::ostream &) const inline virtual
Examples:
AsyncMsg_demo.cpp.
Definition at line 565 of file AsyncMsg.h.
template<typename T > bool Async::Msg::pack (std::ostream & os, const T & val) const inline
Definition at line 570 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2) const inline
Definition at line 586 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3) const inline
Definition at line 602 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4) const inline
Definition at line 618 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5) const inline
Definition at line 637 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6) const inline
Definition at line 659 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7) const inline
Definition at line 684 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8) const inline
Definition at line 711 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8, const T9 & v9) const inline
Definition at line 739 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > bool Async::Msg::pack (std::ostream & os, const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8, const T9 & v9, const T10 & v10) const inline
Definition at line 769 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
virtual size_t Async::Msg::packedSize (void) const inline virtual
Definition at line 566 of file AsyncMsg.h.
template<typename T > size_t Async::Msg::packedSize (const T & val) const inline
Definition at line 575 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2) const inline
Definition at line 591 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3) const inline
Definition at line 607 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4) const inline
Definition at line 624 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5) const inline
Definition at line 644 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6) const inline
Definition at line 667 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7) const inline
Definition at line 692 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8) const inline
Definition at line 720 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8, const T9 & v9) const inline
Definition at line 749 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > size_t Async::Msg::packedSize (const T1 & v1, const T2 & v2, const T3 & v3, const T4 & v4, const T5 & v5, const T6 & v6, const T7 & v7, const T8 & v8, const T9 & v9, const T10 & v10) const inline
Definition at line 779 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
size_t Async::Msg::packedSizeParent (void) const inline
Definition at line 562 of file AsyncMsg.h.
bool Async::Msg::packParent (std::ostream &) const inline
Definition at line 561 of file AsyncMsg.h.
virtual bool Async::Msg::unpack (std::istream &) const inline virtual
Definition at line 567 of file AsyncMsg.h.
template<typename T > bool Async::Msg::unpack (std::istream & is, T & val) const inline
Definition at line 580 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2) inline
Definition at line 596 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3) inline
Definition at line 612 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4) inline
Definition at line 630 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5) inline
Definition at line 651 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5, T6 & v6) inline
Definition at line 675 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5, T6 & v6, T7 & v7) inline
Definition at line 701 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5, T6 & v6, T7 & v7, T8 & v8) inline
Definition at line 729 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5, T6 & v6, T7 & v7, T8 & v8, T9 & v9) inline
Definition at line 759 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
template<typename T1 , typename T2 , typename T3 , typename T4 , typename T5 , typename T6 , typename T7 , typename T8 , typename T9 , typename T10 > bool Async::Msg::unpack (std::istream & is, T1 & v1, T2 & v2, T3 & v3, T4 & v4, T5 & v5, T6 & v6, T7 & v7, T8 & v8, T9 & v9, T10 & v10) inline
Definition at line 790 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
bool Async::Msg::unpackParent (std::istream &) const inline
Definition at line 563 of file AsyncMsg.h.
The documentation for this class was generated from the following file:
AsyncMsg.h