Async: Async::MsgPacker< std::vector< I > > Class Template Reference
Async::MsgPacker< std::vector< I > > Class Template Reference
#include <AsyncMsg.h>
Static Public Member Functions
static bool pack (std::ostream &os, const std::vector< I > &vec)
static size_t packedSize (const std::vector< I > &vec)
static bool unpack (std::istream &is, std::vector< I > &vec)
Detailed Description
template<typename I>
class Async::MsgPacker< std::vector< I > >
Definition at line 448 of file AsyncMsg.h.
Member Function Documentation
pack()
template<typename I > static bool Async::MsgPacker< std::vector< I > >::pack (std::ostream & os, const std::vector< I > & vec) inline static
Definition at line 451 of file AsyncMsg.h.
References Async::MsgPacker< T >::pack().
packedSize()
template<typename I > static size_t Async::MsgPacker< std::vector< I > >::packedSize (const std::vector< I > & vec) inline static
Definition at line 468 of file AsyncMsg.h.
References Async::MsgPacker< T >::packedSize().
unpack()
template<typename I > static bool Async::MsgPacker< std::vector< I > >::unpack (std::istream & is, std::vector< I > & vec) inline static
Definition at line 477 of file AsyncMsg.h.
References Async::MsgPacker< T >::unpack().
The documentation for this class was generated from the following file:
AsyncMsg.h