Async: Async::MsgPacker< T > Class Template Reference
Async::MsgPacker< T > Class Template Reference
#include <AsyncMsg.h>
Static Public Member Functions
static bool pack (std::ostream &os, const T &val)
static size_t packedSize (const T &val)
static bool unpack (std::istream &is, T &val)
Detailed Description
template<typename T>
class Async::MsgPacker< T >
Definition at line 260 of file AsyncMsg.h.
Member Function Documentation
pack()
template<typename T > static bool Async::MsgPacker< T >::pack (std::ostream & os, const T & val) inline static
Definition at line 263 of file AsyncMsg.h.
Referenced by Async::Msg::pack(), Async::MsgPacker< std::map< Tag, Value > >::pack(), Async::MsgPacker< std::string >::pack(), and Async::MsgPacker< std::vector< I > >::pack().
packedSize()
template<typename T > static size_t Async::MsgPacker< T >::packedSize (const T & val) inline static
Definition at line 264 of file AsyncMsg.h.
Referenced by Async::Msg::packedSize(), Async::MsgPacker< std::array< T, N > >::packedSize(), Async::MsgPacker< std::map< Tag, Value > >::packedSize(), Async::MsgPacker< std::set< I > >::packedSize(), Async::MsgPacker< std::vector< I > >::packedSize(), and Async::MsgPacker< T[N]>::packedSize().
unpack()
template<typename T > static bool Async::MsgPacker< T >::unpack (std::istream & is, T & val) inline static
Definition at line 265 of file AsyncMsg.h.
Referenced by Async::Msg::unpack(), Async::MsgPacker< std::map< Tag, Value > >::unpack(), and Async::MsgPacker< std::vector< I > >::unpack().
The documentation for this class was generated from the following file:
AsyncMsg.h