Async: Async::HttpServerConnection::Response Class Reference
Async::HttpServerConnection::Response Class Reference
#include <AsyncHttpServerConnection.h>
Public Member Functions
Response (void)
unsigned code (void) const
void setCode (unsigned code)
const Headers & headers (void) const
template<typename T >
void setHeader (const std::string &key, T value)
const std::string & content (void) const
void setContent (const std::string &content_type, const std::string &content)
bool sendContent (void) const
void setSendContent (bool send_content)
void clear (void)
Detailed Description
Examples
AsyncHttpServer_demo.cpp.
Definition at line 168 of file AsyncHttpServerConnection.h.
Constructor & Destructor Documentation
Response()
Async::HttpServerConnection::Response::Response (void) inline
Definition at line 171 of file AsyncHttpServerConnection.h.
Member Function Documentation
clear()
void Async::HttpServerConnection::Response::clear (void) inline
Definition at line 200 of file AsyncHttpServerConnection.h.
code()
unsigned Async::HttpServerConnection::Response::code (void) const inline
Definition at line 173 of file AsyncHttpServerConnection.h.
Referenced by setCode().
content()
const std::string & Async::HttpServerConnection::Response::content (void) const inline
Definition at line 185 of file AsyncHttpServerConnection.h.
Referenced by setContent().
headers()
const Headers & Async::HttpServerConnection::Response::headers (void) const inline
Definition at line 176 of file AsyncHttpServerConnection.h.
sendContent()
bool Async::HttpServerConnection::Response::sendContent (void) const inline
Definition at line 194 of file AsyncHttpServerConnection.h.
setCode()
void Async::HttpServerConnection::Response::setCode (unsigned code) inline
Examples
AsyncHttpServer_demo.cpp.
Definition at line 174 of file AsyncHttpServerConnection.h.
References code().
setContent()
void Async::HttpServerConnection::Response::setContent (const std::string & content_type, const std::string & content) inline
Examples
AsyncHttpServer_demo.cpp.
Definition at line 186 of file AsyncHttpServerConnection.h.
References content(), setHeader(), and setSendContent().
setHeader()
template<typename T > void Async::HttpServerConnection::Response::setHeader (const std::string & key, T value) inline
Definition at line 178 of file AsyncHttpServerConnection.h.
Referenced by setContent().
setSendContent()
void Async::HttpServerConnection::Response::setSendContent (bool send_content) inline
Examples
AsyncHttpServer_demo.cpp.
Definition at line 195 of file AsyncHttpServerConnection.h.
Referenced by setContent().
The documentation for this class was generated from the following file:
AsyncHttpServerConnection.h